FROM node:14.16.1-alpine3.13

ARG NODE_ENV="production"

RUN mkdir ./server

RUN mkdir -p /var/www/html/


WORKDIR /server

COPY package*.json ./

RUN npm install -g sequelize-cli

RUN npm install

COPY . .

EXPOSE 3000

CMD sequelize db:migrate && sequelize db:seed:all && npm server
