"use strict";
const CONSTANTS = Object.freeze({
  JWT_SECRET_ACCESS: "asdasdasd4as5d4as8d7a8sd4as65d4a8sd7asd4as56d4",
  JWT_SECRET_REFRESH: "4d65sa4dsa7ds8a4d56sa4ds8a7d8sa4d5sa4dsadsadsa",
  ACCESS_TOKEN_TIME: 60 * 5,
  REFRESH_TOKEN_TIME: "30d",
  SALT_ROUNDS: 5,
  SQUADHELP_BANK_NUMBER: "4564654564564564",
  SQUADHELP_BANK_NAME: "SquadHelp",
  SQUADHELP_BANK_CVC: "453",
  SQUADHELP_BANK_EXPIRY: "11/23",
  CUSTOMER: "customer",
  CREATOR: "creator",
  MODER: "moderator",
  CREATOR_ENTRIES: "creator_entries",
  CONTEST_STATUS_ACTIVE: "active",
  CONTEST_STATUS_FINISHED: "finished",
  CONTEST_STATUS_PENDING: "pending",
  CONTESTS_DEFAULT_DIR: "public/contestFiles/",
  AVATAR_DIR: "images_avatar",
  OFFER_IMAGES_DIR: "images_logo",
  CONTEST_FILE_DIR: "contest_files",
  NAME_CONTEST: "name",
  LOGO_CONTEST: "logo",
  TAGLINE_CONTEST: "tagline",
  OFFER_STATUS_PENDING: "pending",
  OFFER_STATUS_REJECTED: "rejected",
  OFFER_STATUS_WON: "won",
  FILES_PATH: "public/",
  SOCKET_CONNECTION: "connection",
  SOCKET_SUBSCRIBE: "subscribe",
  SOCKET_UNSUBSCRIBE: "unsubscribe",
  NOTIFICATION_ENTRY_CREATED: "onEntryCreated",
  NOTIFICATION_CHANGE_MARK: "changeMark",
  NOTIFICATION_CHANGE_OFFER_STATUS: "changeOfferStatus",
  NEW_MESSAGE: "newMessage",
  CHANGE_BLOCK_STATUS: "CHANGE_BLOCK_STATUS",
  STATUS_MODERATION: {
    INSPECTION: "inspection",
    PASSED: "passed",
    BANNED: "banned",
  },
  NODEMAILER: {
    SMTP: "smtp.ethereal.email",
    PORT: 587,
    AUTH: {
      user: "janet.aufderhar1@ethereal.email",
      pass: "j3aPvfDDPHqHqmSF5J",
    },
  },
  CONTEST: "contest",
  OFFER: "offer",
});

module.exports = CONSTANTS;
